const ar=document.documentElement.lang==='ar';
const toggle=document.querySelector('.menu-toggle');const links=document.querySelector('.links');
function closeMenu(){toggle?.setAttribute('aria-expanded','false');links?.classList.remove('open')}
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));links.classList.toggle('open',open)});
links?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}},{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}
const filters=document.querySelectorAll('.filter');const grid=document.querySelector('.gallery-grid');filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const value=button.dataset.filter;document.querySelectorAll('.gallery-card').forEach(card=>card.hidden=value!=='all'&&card.dataset.category!==value);grid.classList.toggle('filtered',value!=='all')}));
const dialog=document.querySelector('.lightbox');let opener;
document.querySelectorAll('[data-lightbox]').forEach(b=>b.addEventListener('click',()=>{opener=b;dialog.querySelector('img').src=b.querySelector('img').src;dialog.querySelector('img').alt=b.querySelector('img').alt;dialog.querySelector('.lightbox-label').textContent=b.dataset.caption;dialog.showModal()}));
dialog?.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog?.addEventListener('close',()=>opener?.focus());
document.querySelectorAll('[data-service]').forEach(a=>a.addEventListener('click',()=>{const select=document.querySelector('[name=service]');if(select&&Array.from(select.options).some(o=>o.value===a.dataset.service))select.value=a.dataset.service}));
const form=document.querySelector('form');form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);const name=String(data.get('name')).trim();if(!name){form.querySelector('[name=name]').setCustomValidity(ar?'اكتب اسمك للتعريف بالطلب':'Please enter your name');form.reportValidity();return}const phone=String(data.get('phone')).trim();const message=ar?`مرحبًا ${form.dataset.business}، أرغب في الاستفسار.\nالاسم: ${name}\nالخدمة: ${data.get('service')}\nاليوم المفضل: ${data.get('date')||'لم يحدد'}\n${phone?'رقم التواصل: '+phone+'\n':''}التفاصيل: ${String(data.get('details')).trim()}\nأرجو تأكيد الخيارات والتكلفة والتوافر.`:`Hello ${form.dataset.business}, I would like to enquire.\nName: ${name}\nService: ${data.get('service')}\nPreferred day: ${data.get('date')||'Not specified'}\n${phone?'Contact number: '+phone+'\n':''}Details: ${String(data.get('details')).trim()}\nPlease confirm the options, price and availability.`;
const result=form.querySelector('.form-result');result.hidden=false;result.querySelector('a').href=`https://wa.me/${form.dataset.phone}?text=${encodeURIComponent(message)}`;result.querySelector('.message-preview').textContent=message;form.querySelector('.form-feedback').textContent=ar?'تم تجهيز الاستفسار. راجعه ثم افتح واتساب. لم تُرسل أي رسالة.':'Your enquiry is ready. Review it, then open WhatsApp. No message has been sent.';result.scrollIntoView({behavior:'smooth',block:'nearest'})});
form?.querySelector('[name=name]').addEventListener('input',e=>e.target.setCustomValidity(''));
const date=form?.querySelector('[name=date]');if(date){const d=new Date();date.min=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
